// filtersData
export const GET_FILTERS_DATA_REQUEST = 'GET_FILTERS_DATA_REQUEST';
export const GET_FILTERS_DATA_SUCCESS = 'GET_FILTERS_DATA_SUCCESS';
export const GET_FILTERS_DATA_FAILURE = 'GET_FILTERS_DATA_FAILURE';
export const ADD_SELECTED_ENTRY = 'ADD_SELECTED_ENTRY';
export const REMOVE_SELECTED_ENTRY = 'REMOVE_SELECTED_ENTRY';
