// filtersData
export const GET_FILTERS_DATA_REQUEST = 'GET_FILTERS_DATA_REQUEST';
export const GET_FILTERS_DATA_SUCCESS = 'GET_FILTERS_DATA_SUCCESS';
export const GET_FILTERS_DATA_FAILURE = 'GET_FILTERS_DATA_FAILURE';
export const TOGGLE_SELECTED_ENTRY = 'TOGGLE_SELECTED_ENTRY';
