// filtersData
export const GET_FILTERS_DATA_REQUEST = 'GET_FILTERS_DATA_REQUEST';
export const GET_FILTERS_DATA_SUCCESS = 'GET_FILTERS_DATA_SUCCESS';
export const GET_FILTERS_DATA_FAILURE = 'GET_FILTERS_DATA_FAILURE';
export const TOGGLE_SELECTED_ENTRY = 'TOGGLE_SELECTED_ENTRY';
export const TOGGLE_EXPAND_CATEGORY = 'TOGGLE_EXPAND_CATEGORY';
export const RESET_CATEGORY_SELECTIONS = 'RESET_CATEGORY_SELECTIONS';
export const SET_SEARCH_CATEGORY = 'SET_SEARCH_CATEGORY';
export const RESET_SEARCH_CATEGORY = 'RESET_SEARCH_CATEGORY';

// search
export const SHOW_TOOLTIP = 'SHOW_TOOLTIP';
export const HIDE_TOOLTIP = 'HIDE_TOOLTIP';
